[colors.primary]
background = "#222218"
foreground = "#cccccc"

[colors.normal]
black = "#444444"
red = "#aaaaaa"
green = "#aaaaaa"
yellow = "#aaaaaa"
blue = "#aaaaaa"
magenta = "#aaaaaa"
cyan = "#aaaaaa"
white = "#cccccc"

[colors.bright]
black = "#555555"
red = "#aaaaaa"
green = "#aaaaaa"
yellow = "#aaaaaa"
blue = "#aaaaaa"
magenta = "#aaaaaa"
cyan = "#aaaaaa"
white = "#bbbbbb"
