#!/usr/bin/env bash

export SCRIPT_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${SCRIPT_LOCATION}/scripts/style.sh"
source "${SCRIPT_LOCATION}/scripts/link.sh"

__FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -f|--force)
      __FORCE=true
      ;;
    *)
      ;;
  esac
  shift
done

echo
echo -e "$(printPrimaryMessage "Installing dotfiles")"


__handle_links "install" ${__FORCE}

for dir in "common" "$(uname)"; do
  if [ -d "${SCRIPT_LOCATION}/${dir}/recipes" ]; then
    for recipe in "${SCRIPT_LOCATION}/${dir}/recipes/"*.sh; do
      bash "$recipe"
    done
  fi
done

for dir in "common" "$(uname)"; do
  if [ -d "${SCRIPT_LOCATION}/${dir}/post_install" ]; then
    for post_install in "${SCRIPT_LOCATION}/${dir}/post_install/"*.sh; do
      bash "$post_install"
    done
  fi
done

echo -e "$(printPrimaryMessage "Installation of dotfiles completed")"
echo
