#!/usr/bin/env bash

export SCRIPT_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${SCRIPT_LOCATION}/scripts/style.sh"

echo
echo -e "$(printPrimaryMessage "Installing dotfiles")"

bash "${SCRIPT_LOCATION}/scripts/link.sh"
bash "${SCRIPT_LOCATION}/common/recipes/asdf.sh"
bash "${SCRIPT_LOCATION}/common/recipes/zplug.sh"
bash "${SCRIPT_LOCATION}/common/recipes/vim-plug.sh"
bash "${SCRIPT_LOCATION}/common/recipes/sdkman.sh"
bash "${SCRIPT_LOCATION}/common/recipes/tpm.sh"

echo -e "$(printPrimaryMessage "Installation of dotfiles completed")"
echo
