#!/usr/bin/env bash

SCRIPT_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${SCRIPT_LOCATION}/scripts/style.sh"

__FORCE=false
__SEARCH=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -f|--force)
      __FORCE=true
      ;;
    -s|--search)
      __SEARCH=true
      ;;
    *)
      ;;
  esac
  shift
done

if [[ "$__SEARCH" = "true" ]]; then
    source "${SCRIPT_LOCATION}/scripts/link.sh"
    __handle_links "uninstall" $__FORCE
    rm "${HOME}/.dotfiles_uninstall.txt"
else
    if [ -f "${HOME}/.dotfiles_uninstall.txt" ]; then
        while IFS= read -r line
        do
            echo -e "$(printWarningMessage "Removing ${line}")"
            rm "${line}"
        done < <(cat "${HOME}/.dotfiles_uninstall.txt")
        rm "${HOME}/.dotfiles_uninstall.txt"
    else
        echo -e "$(printWarningMessage "No uninstall file found at ${HOME}/.dotfiles_uninstall.txt")"
        echo -e "$(printWarningMessage "Nothing to uninstall")"
    fi
fi