#!/usr/bin/env bash

# Copyright (c) 2025 Indrajit Roy
# Part of "dotfiles", licensed under GNU AGPLv3 or later
# See https://opensource.org/license/agpl-v3 for details.

SCRIPT_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" && export SCRIPT_LOCATION

# directories
__FUNCTIONS_DIR="${SCRIPT_LOCATION}/__functions"
__BEFORE_DIR="${SCRIPT_LOCATION}/__before_dots"
__AFTER_DIR="${SCRIPT_LOCATION}/__dots_after"
__DOTS_DIR="${SCRIPT_LOCATION}/__dots"

source "${__DOTS_DIR}/rel:.local/share/bash/lib/ansi_text_style.sh.generic.symlink"

for file in "${__FUNCTIONS_DIR}/"*.sh; do
  # shellcheck source=__functions/*.sh
  source "${file}"
done

__VERBOSE=false __FORCE=false __STATUS=false __DRY=false

__parse_common_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -s|--status ) __STATUS=true  ;;
      -v|--verbose) __VERBOSE=true ;;
      -f|--force  ) __FORCE=true   ;;
      -d|--dry    ) __DRY=true     ;;
      *) ;;
    esac
    shift
  done
}

export __VERBOSE __FORCE __STATUS __DRY

case "$1" in
  h|help     ) shift;                           __help     ; exit 0 ;;
  l|list     ) shift; __parse_common_args "$@"; __list     ; exit 0 ;;
  i|install  ) shift; __parse_common_args "$@"; __install  ; exit 0 ;;
  u|uninstall) shift; __parse_common_args "$@"; __uninstall; exit 0 ;;
  *          ) shift;                           __help     ; exit 0 ;;
esac
