#!/usr/bin/env bash

echo
echo -e "  \033[94m ==> \033[39m"
echo -e "  \033[94m ==> \033[32mInstalling dotfiles \033[39m"

echo -e "  \033[94m ==> \033[39m"
echo -e "  \033[94m ==> \033[32mInitializing submodule(s) \033[39m"
git submodule update --init --recursive
git submodule foreach pull origin master

bash link.sh
bash copy.sh
bash common/recipes/antigen.sh
bash common/recipes/zplug.sh
bash common/recipes/tpm.sh
bash common/recipes/hg-color.sh
bash common/recipes/vim-plug.sh
bash common/recipes/sdkman.sh

echo -e "  \033[94m ==> \033[39m"
echo -e "  \033[94m ==> \033[32mInstallation of dotfiles completed. \033[39m"
echo -e "  \033[94m ==> \033[39m"
echo
