#!/usr/bin/env bash

echo "Installing dotfiles"

echo "Initializing submodule(s)"
git submodule update --init --recursive
git submodule foreach pull origin master

bash link.sh
bash copy.sh
bash common/recipes/antigen.sh
bash common/recipes/zplug.sh
bash common/recipes/tpm.sh
bash common/recipes/hg-color.sh
bash common/recipes/vim-plug.sh
bash common/recipes/sdkman.sh
compinit

