[colors]
primary.background = "0x181815"
primary.foreground = "0xaaaaaa"

[colors.normal]
black = "0x3a3a3a"
red = "0x8f6f6f"
green = "0x6f7f6f"
yellow = "0x7f7f5f"
blue = "0x6f6f7f"
magenta = "0x7f6f7f"
cyan = "0x6f7f7f"
white = "0x909090"

[colors.bright]
black = "0x444444"
red = "0x8f5f5f"
green = "0x6f8a6f"
yellow = "0x8f8f6f"
blue = "0x5f5f7f"
magenta = "0x7f5f7f"
cyan = "0x5f7f7f"
white = "0xa6a6a6"
