[window]
dimensions = { columns = 170, lines = 50 }
position  = "None"
padding = { x = 5, y = 5 }
dynamic_padding = false
decorations = "Buttonless"
opacity = 1.0
blur = false
startup_mode = "FullScreen"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"
resize_increments = false
option_as_alt = "None"
level = "Normal"
