# TAPS

# SHELLS
cask "alacritty"
brew "bash"
brew "bash-completion"
cask "iterm2"
brew "shellcheck"
brew "tmux"
brew "zsh"

# VCS
brew "git"
brew "git-crypt"
brew "git-extras"
brew "git-sizer"
brew "git-lfs"
brew "gitleaks"

# EDITORS
brew "neovim"
cask "table-tool"
cask "textmate"
cask "visual-studio-code"

# LINUX/UNIX TOOLS
brew "curl"
brew "coreutils"
brew "findutils"
brew "moreutils"
brew "tree"
brew "watch"
brew "wget"

# HARDWARE TOOLS
brew "e2fsprogs" # e2fsprogs is a set of utilities for managing ext2/ext3/ext4 filesystems
brew "fsql"
brew "gromgit/fuse/ntfs-3g-mac"
brew "htop"
brew "lsusb"
cask "macfuse"
cask "mounty"
brew "ncdu"

# UTILITY TOOLS
cask "android-platform-tools"
brew "asciinema"
brew "direnv"
cask "espanso"
brew "eza"
brew "f3" # f3 is a tool to test the real capacity of USB flash drives
brew "fzf"
brew "jq"
cask "keka"
brew "libgit2"
brew "multitail"
brew "pv"
brew "ripgrep" # ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern
cask "sf-symbols"
cask "stats"
brew "the_silver_searcher" # The Silver Searcher is a code-searching tool similar to ack, but faster
brew "yank"
brew "yq"
brew "zoxide"

# NETWORKING TOOLS
brew "nmap"
brew "openconnect"
brew "openssh"
brew "rustscan"
brew "sshuttle"
brew "vpn-slice"
brew "wireshark"
cask "wireshark-chmodbpf"

# BROWSERS
cask "google-chrome"
cask "tor-browser"

# DEVELOPMENT TOOLS
cask "jetbrains-toolbox"
brew "k6"
brew "loc"
brew "openjdk"
cask "postman"
brew "python@3.11"
brew "ruby"
cask "visualvm"

# DATABASE TOOLS
brew "postgresql@17", restart_service: :changed

# CONTAINERS, VIRTUALIZATION & ORCHESTRATION
brew "ansible"
brew "helm"
brew "minikube"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"

# FONTS
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"

# SECURITY
cask "gpg-suite"
cask "veracrypt"

# OTHERS
cask "intune-company-portal"
cask "vlc"
cask "whatsapp"
