[colors.primary]
background = "#ffffff"
foreground = "#222222"

[colors.normal]
black = "#222222"
red = "#303030"
green = "#303030"
yellow = "#303030"
blue = "#303030"
magenta = "#303030"
cyan = "#303030"
white = "#999999"

[colors.bright]
black = "#333333"
red = "#3f3f3f"
green = "#3f3f3f"
yellow = "#3f3f3f"
blue = "#3f3f3f"
magenta = "#3f3f3f"
cyan = "#3f3f3f"
white = "#888888"
