[colors]
primary.background = "0x1c1b1b"
primary.foreground = "0xcecece"

[colors.normal]
black = "0x848383"
red = "0xbf9494"
green = "0x567573"
yellow = "0xb2a245"
blue = "0x5487b6"
magenta = "0xbc98ac"
cyan = "0x94b5ae"
white = "0xcecece"

[colors.bright]
black = "0x838383"
red = "0xeedbdb"
green = "0x4e7c74"
yellow = "0xd8c65d"
blue = "0x5e97cb"
magenta = "0xc685a9"
cyan = "0x85bfb3"
white = "0x939292"
