[colors]
primary.background = "0x222222"
primary.foreground = "0xcccccc"

[colors.normal]
black = "0x444444"
red = "0xaaaaaa"
green = "0xaaaaaa"
yellow = "0xaaaaaa"
blue = "0xaaaaaa"
magenta = "0xaaaaaa"
cyan = "0xaaaaaa"
white = "0xcccccc"

[colors.bright]
black = "0x555555"
red = "0xaaaaaa"
green = "0xaaaaaa"
yellow = "0xaaaaaa"
blue = "0xaaaaaa"
magenta = "0xaaaaaa"
cyan = "0xaaaaaa"
white = "0xbbbbbb"