[colors]
primary.background = "0x181815"
primary.foreground = "0xaaaaaa"

[colors.normal]
black = "0x3a3a3a"
red = "0x8f4f4f"
green = "0x4f6f4f"
yellow = "0x7f7f4f"
blue = "0x7995b2"
magenta = "0x864f86"
cyan = "0x4f8f8f"
white = "0x999999"

[colors.bright]
black = "0x444444"
red = "0xaf4f4f"
green = "0x4f7f4f"
yellow = "0x8a8a3f"
blue = "0x779ec4"
magenta = "0x8f4f8f"
cyan = "0x4f9a9a"
white = "0xaaaaaa"
