[colors.primary]
background = "#aaaaa1"
foreground = "#222222"

[colors.normal]
black = "#222222"
red = "#6f3f3f"
green = "#3f6f3f"
yellow = "#6f6f3f"
blue = "#3f3f6f"
magenta = "#6f3f6f"
cyan = "#3f6f6f"
white = "#bbbbbb"

[colors.bright]
black = "#333333"
red = "#7f3f3f"
green = "#3f7f3f"
yellow = "#7f7f3f"
blue = "#3f3f7f"
magenta = "#7f3f7f"
cyan = "#3f7f7f"
white = "#cccccc"
