[colors.primary]
background = "#bbbbaa"
foreground = "#222222"

[colors.normal]
black = "#222222"
red = "#3f3f3f"
green = "#3f3f3f"
yellow = "#3f3f3f"
blue = "#3f3f3f"
magenta = "#3f3f3f"
cyan = "#3f3f3f"
white = "#aaaaaa"

[colors.bright]
black = "#333333"
red = "#3f3f3f"
green = "#3f3f3f"
yellow = "#3f3f3f"
blue = "#3f3f3f"
magenta = "#3f3f3f"
cyan = "#3f3f3f"
white = "#bbbbbb"
