env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 75
    lines: 11
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3
  multiplier: 3

draw_bold_text_with_bright_colors: true

font:
  antialias: true
  # normal:
  #   family: "MesloLGMDZ Nerd Font"
  #   style: RegularForPowerline
  # bold:
  #   family: "MesloLGMDZ Nerd Font"
  #   style: RegularForPowerline
  # italic:
  #   family: "MesloLGMDZ Nerd Font"
  #   style: RegularForPowerline

  size: 15.0

  offset:
    x: -2
    y: -2

  glyph_offset:
    x: 0
    y: 0

debug:
  render_timer: false

  persistent_logging: false

# Colors (Challenger Deep)
colors:
  # Default colors
  primary:
    background: '0x1e1c31'
    foreground: '0xcbe1e7'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xff271d'
    cursor: '0xfbfcfc'
  # Normal colors
  normal:
    black:   '0x141228'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'
  # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'



# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Values for `animation`:
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
#
# Specifying a `duration` of `0` will disable the visual bell.
bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

# Mouse bindings
#
# Available fields:
#   - mouse
#   - action
#   - mods (optional)
#
# Values for `mouse`:
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  unfocused_hollow: true

live_config_reload: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
shell:
#  program: tmux
#  args:
#    - --login

# Key bindings
#
# Key bindings are specified as a list of objects. Each binding will specify
# a key and modifiers required to trigger it, terminal modes where the binding
# is applicable, and what should be done when the key binding fires. It can
# either send a byte sequence to the running application (`chars`), execute
# a predefined action (`action`) or fork and execute a specified command plus
# arguments (`command`).
#
# Example:
#   `- { key: V, mods: Control|Shift, action: Paste }`
#
# Available fields:
#   - key
#   - mods (optional)
#   - chars | action | command (exactly one required)
#   - mode (optional)
#
# Values for `key`:
#   - `A` -> `Z`
#   - `F1` -> `F12`
#   - `Key1` -> `Key0`
#
#   A full list with available key codes can be found here:
#   https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
#   Instead of using the name of the keys, the `key` field also supports using
#   the scancode of the desired key. Scancodes have to be specified as a
#   decimal number.
#   This command will allow you to display the hex scancodes for certain keys:
#     `showkey --scancodes`
#
# Values for `mods`:
#   - Command
#   - Control
#   - Shift
#   - Alt
#
#   Multiple `mods` can be combined using `|` like this: `mods: Control|Shift`.
#   Whitespace and capitalization is relevant and must match the example.
#
# Values for `chars`:
#   The `chars` field writes the specified string to the terminal. This makes
#   it possible to pass escape sequences.
#   To find escape codes for bindings like `PageUp` ("\x1b[5~"), you can run
#   the command `showkey -a` outside of tmux.
#   Note that applications use terminfo to map escape sequences back to
#   keys. It is therefore required to update the terminfo when
#   changing an escape sequence.
#
# Values for `action`:
#   - Paste
#   - PasteSelection
#   - Copy
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#   - Hide
#   - Quit
#   - ClearLogNotice
#   - SpawnNewInstance
#
# Values for `command`:
#   The `command` field must be a map containing a `program` string and
#   an `args` array of command line parameter strings.
#
#   Example:
#       `command: { program: "alacritty", args: ["-e", "vttest"] }`
#
# Values for `mode`:
#   - ~AppCursor
#   - AppCursor
#   - ~AppKeypad
#   - AppKeypad
key_bindings:
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }

  # Vi Mode
  - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
  - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }
  - { key: Escape,                      mode: Vi|~Search, action: ClearSelection          }
  - { key: I,                           mode: Vi|~Search, action: ToggleViMode            }
  - { key: I,                           mode: Vi|~Search, action: ScrollToBottom          }
  - { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode            }
  - { key: Y,      mods: Control,       mode: Vi|~Search, action: ScrollLineUp            }
  - { key: E,      mods: Control,       mode: Vi|~Search, action: ScrollLineDown          }
  - { key: G,                           mode: Vi|~Search, action: ScrollToTop             }
  - { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom          }
  - { key: B,      mods: Control,       mode: Vi|~Search, action: ScrollPageUp            }
  - { key: F,      mods: Control,       mode: Vi|~Search, action: ScrollPageDown          }
  - { key: U,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageUp        }
  - { key: D,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageDown      }
  - { key: Y,                           mode: Vi|~Search, action: Copy                    }
  - { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
  - { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
  - { key: V,                           mode: Vi|~Search, action: ToggleNormalSelection   }
  - { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
  - { key: V,      mods: Control,       mode: Vi|~Search, action: ToggleBlockSelection    }
  - { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
  - { key: Return,                      mode: Vi|~Search, action: Open                    }
  - { key: K,                           mode: Vi|~Search, action: Up                      }
  - { key: J,                           mode: Vi|~Search, action: Down                    }
  - { key: H,                           mode: Vi|~Search, action: Left                    }
  - { key: L,                           mode: Vi|~Search, action: Right                   }
  - { key: Up,                          mode: Vi|~Search, action: Up                      }
  - { key: Down,                        mode: Vi|~Search, action: Down                    }
  - { key: Left,                        mode: Vi|~Search, action: Left                    }
  - { key: Right,                       mode: Vi|~Search, action: Right                   }
  - { key: Key0,                        mode: Vi|~Search, action: First                   }
  - { key: Key4,   mods: Shift,         mode: Vi|~Search, action: Last                    }
  - { key: Key6,   mods: Shift,         mode: Vi|~Search, action: FirstOccupied           }
  - { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
  - { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
  - { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
  - { key: B,                           mode: Vi|~Search, action: SemanticLeft            }
  - { key: W,                           mode: Vi|~Search, action: SemanticRight           }
  - { key: E,                           mode: Vi|~Search, action: SemanticRightEnd        }
  - { key: B,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
  - { key: W,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
  - { key: E,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
  - { key: Key5,   mods: Shift,         mode: Vi|~Search, action: Bracket                 }
  - { key: Slash,                       mode: Vi|~Search, action: SearchForward           }
  - { key: Slash,  mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
  - { key: N,                           mode: Vi|~Search, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }

  # Search Mode
  - { key: Return,                mode: Search|Vi,  action: SearchConfirm         }
  - { key: Escape,                mode: Search,     action: SearchCancel          }
  - { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
  - { key: U,      mods: Control, mode: Search,     action: SearchClear           }
  - { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
  - { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
  - { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
  - { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
  - { key: Down,                  mode: Search,     action: SearchHistoryNext     }
  - { key: Return,                mode: Search|~Vi, action: SearchFocusNext       }
  - { key: Return, mods: Shift,   mode: Search|~Vi, action: SearchFocusPrevious   }

  # (Windows, Linux, and BSD only)
  #- { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  #- { key: C,              mods: Control|Shift,                   action: Copy             }
  #- { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  #- { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
  #- { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
  #- { key: Insert,         mods: Shift,                           action: PasteSelection   }
  #- { key: Key0,           mods: Control,                         action: ResetFontSize    }
  #- { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  #- { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  #- { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  #- { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  #- { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }

  # (Windows only)
  #- { key: Return,   mods: Alt,           action: ToggleFullscreen }

  # (macOS only)
  - { key: K,              mods: Command, mode: ~Vi|~Search, chars: "\x0c"                 }
  - { key: K,              mods: Command, mode: ~Vi|~Search, action: ClearHistory          }
  - { key: Key0,           mods: Command,                    action: ResetFontSize         }
  - { key: Equals,         mods: Command,                    action: IncreaseFontSize      }
  - { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
  - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
  - { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
  - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
  - { key: V,              mods: Command,                    action: Paste                 }
  - { key: C,              mods: Command,                    action: Copy                  }
  - { key: C,              mods: Command, mode: Vi|~Search,  action: ClearSelection        }
  - { key: H,              mods: Command,                    action: Hide                  }
  - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  - { key: M,              mods: Command,                    action: Minimize              }
  - { key: Q,              mods: Command,                    action: Quit                  }
  - { key: W,              mods: Command,                    action: Quit                  }
  - { key: N,              mods: Command,                    action: SpawnNewInstance      }
  - { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
  - { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
  - { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }
