[debug]
persistent_logging = false
render_timer = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[general]
import = [
    "~/.config/alacritty/env.toml",
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/mouse.toml",
    "~/.config/alacritty/theme.toml",
    "~/.config/alacritty/window.toml",
]
working_directory = "None"
live_config_reload = true
ipc_socket = true
