[general]
import = [
    "~/.config/alacritty/debug.toml",
    "~/.config/alacritty/env.toml",
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/mouse.toml",
    "~/.config/alacritty/visual.toml",
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/theme/nord.toml",
]
working_directory = "~"
live_config_reload = true
ipc_socket = true

[scrolling]
history = 1_00_000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s default"]

