[keyboard]
bindings = [
    { action = "Paste", key = "Paste" },
    { action = "Copy", key = "Copy" },
    { action = "ClearLogNotice", key = "L", mods = "Control" },
    { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "Shift" },
    { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
    { action = "ToggleViMode", key = "Space", mode = "~Search", mods = "Shift|Control" },
    { action = "ScrollToBottom", key = "Space", mode = "Vi|~Search", mods = "Shift|Control" },
    { action = "ClearSelection", key = "Escape", mode = "Vi|~Search" },
    { action = "ToggleViMode", key = "I", mode = "Vi|~Search" },
    { action = "ScrollToBottom", key = "I", mode = "Vi|~Search" },
    { action = "ToggleViMode", key = "C", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollLineUp", key = "Y", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollLineDown", key = "E", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollToTop", key = "G", mode = "Vi|~Search" },
    { action = "ScrollToBottom", key = "G", mode = "Vi|~Search", mods = "Shift" },
    { action = "ScrollPageUp", key = "B", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollPageDown", key = "F", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageUp", key = "U", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageDown", key = "D", mode = "Vi|~Search", mods = "Control" },
    { action = "Copy", key = "Y", mode = "Vi|~Search" },
    { action = "ClearSelection", key = "Y", mode = "Vi|~Search" },
    { action = "ClearSelection", key = "Copy", mode = "Vi|~Search" },
    { action = "ToggleNormalSelection", key = "V", mode = "Vi|~Search" },
    { action = "ToggleLineSelection", key = "V", mode = "Vi|~Search", mods = "Shift" },
    { action = "ToggleBlockSelection", key = "V", mode = "Vi|~Search", mods = "Control" },
    { action = "ToggleSemanticSelection", key = "V", mode = "Vi|~Search", mods = "Alt" },
    { action = "Open", key = "Return", mode = "Vi|~Search" },
    { action = "Up", key = "K", mode = "Vi|~Search" },
    { action = "Down", key = "J", mode = "Vi|~Search" },
    { action = "Left", key = "H", mode = "Vi|~Search" },
    { action = "Right", key = "L", mode = "Vi|~Search" },
    { action = "Up", key = "Up", mode = "Vi|~Search" },
    { action = "Down", key = "Down", mode = "Vi|~Search" },
    { action = "Left", key = "Left", mode = "Vi|~Search" },
    { action = "Right", key = "Right", mode = "Vi|~Search" },
    { action = "First", key = "Key0", mode = "Vi|~Search" },
    { action = "Last", key = "Key4", mode = "Vi|~Search", mods = "Shift" },
    { action = "FirstOccupied", key = "Key6", mode = "Vi|~Search", mods = "Shift" },
    { action = "High", key = "H", mode = "Vi|~Search", mods = "Shift" },
    { action = "Middle", key = "M", mode = "Vi|~Search", mods = "Shift" },
    { action = "Low", key = "L", mode = "Vi|~Search", mods = "Shift" },
    { action = "SemanticLeft", key = "B", mode = "Vi|~Search" },
    { action = "SemanticRight", key = "W", mode = "Vi|~Search" },
    { action = "SemanticRightEnd", key = "E", mode = "Vi|~Search" },
    { action = "WordLeft", key = "B", mode = "Vi|~Search", mods = "Shift" },
    { action = "WordRight", key = "W", mode = "Vi|~Search", mods = "Shift" },
    { action = "WordRightEnd", key = "E", mode = "Vi|~Search", mods = "Shift" },
    { action = "Bracket", key = "Key5", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchForward", key = "Slash", mode = "Vi|~Search" },
    { action = "SearchBackward", key = "Slash", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchNext", key = "N", mode = "Vi|~Search" },
    { action = "SearchPrevious", key = "N", mode = "Vi|~Search", mods = "Shift" },
    { action = "SearchConfirm", key = "Return", mode = "Search|Vi" },
    { action = "SearchCancel", key = "Escape", mode = "Search" },
    { action = "SearchCancel", key = "C", mode = "Search", mods = "Control" },
    { action = "SearchClear", key = "U", mode = "Search", mods = "Control" },
    { action = "SearchDeleteWord", key = "W", mode = "Search", mods = "Control" },
    { action = "SearchHistoryPrevious", key = "P", mode = "Search", mods = "Control" },
    { action = "SearchHistoryNext", key = "N", mode = "Search", mods = "Control" },
    { action = "SearchHistoryPrevious", key = "Up", mode = "Search" },
    { action = "SearchHistoryNext", key = "Down", mode = "Search" },
    { action = "SearchFocusNext", key = "Return", mode = "Search|~Vi" },
    { action = "SearchFocusPrevious", key = "Return", mode = "Search|~Vi", mods = "Shift" },
    { action = "ClearHistory", key = "K", mode = "~Vi|~Search", mods = "Command" },
    { action = "ResetFontSize", key = "Key0", mods = "Command" },
    { action = "IncreaseFontSize", key = "Equals", mods = "Command" },
    { action = "IncreaseFontSize", key = "Plus", mods = "Command" },
    { action = "IncreaseFontSize", key = "NumpadAdd", mods = "Command" },
    { action = "DecreaseFontSize", key = "Minus", mods = "Command" },
    { action = "DecreaseFontSize", key = "NumpadSubtract", mods = "Command" },
    { action = "Paste", key = "V", mods = "Command" },
    { action = "Copy", key = "C", mods = "Command" },
    { action = "ClearSelection", key = "C", mode = "Vi|~Search", mods = "Command" },
    { action = "Hide", key = "H", mods = "Command" },
    { action = "HideOtherApplications", key = "H", mods = "Command|Alt" },
    { action = "Minimize", key = "M", mods = "Command" },
    { action = "Quit", key = "Q", mods = "Command" },
    { action = "Quit", key = "W", mods = "Command" },
    { action = "SpawnNewInstance", key = "N", mods = "Command" },
    { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
    { action = "ToggleFullscreen", key = "Return", mods = "Command" },
    { action = "SearchForward", key = "F", mode = "~Search", mods = "Command" },
    { action = "SearchBackward", key = "B", mode = "~Search", mods = "Command" },
    { chars = "\f", key = "L", mode = "~Vi|~Search", mods = "Control" },
    { chars = "\f", key = "K", mode = "~Vi|~Search", mods = "Command" },
]