[colors]
primary.background = "0x1c1b1b"
primary.foreground = "0xcecece"

[colors.normal]
black = "0x848383"
red = "0xd69192"
green = "0xadbc95"
yellow = "0xbfbf83"
blue = "0x90aab2"
magenta = "0xbc98ac"
cyan = "0x94b5ae"
white = "0xcecece"

[colors.bright]
black = "0x838383"
red = "0xdb7f80"
green = "0xa8c47b"
yellow = "0xd1d16c"
blue = "0x7cacbc"
magenta = "0xc685a9"
cyan = "0x85bfb3"
white = "0x939292"
