[colors]
primary.background = "0xaaa9a9"
primary.foreground = "0x2d2d2d"

[colors.normal]
black = "0x2d2d2d"
red = "0x562424"
green = "0x2b4f21"
yellow = "0x515124"
blue = "0x1f3244"
magenta = "0x4a1a3a"
cyan = "0x193f3f"
white = "0xafaeae"

[colors.bright]
black = "0x545353"
red = "0x723434"
green = "0x3d6832"
yellow = "0x6d6d36"
blue = "0x334a60"
magenta = "0x6a3a5a"
cyan = "0x2a5656"
white = "0xd3d1d1"
